name: Update Internships CSV

on:
  schedule:
    - cron: '0 * * * *'   # every hour
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install git
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Run extractor
        run: python3 fetch_and_extract.py

      - name: Commit and push CSV
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add internships_us_canada.csv || true
          if ! git diff --staged --quiet; then
            git commit -m "Hourly update: internships CSV"
            git push https://x-access-token:${GH_PAT}@github.com/vats98754/job-fetcher.git HEAD:main
          else
            echo "No changes to commit"
          fi
