name: Update Internships CSV

on:
  schedule:
    - cron: '0 * * * *'   # every hour
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run extractor
        run: python3 fetch_and_extract.py

      - name: Commit and push CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Check if there are any changes
          git add internships_us_canada.csv || true
          if ! git diff --staged --quiet; then
            echo "Changes detected, committing and pushing..."
            git commit -m "Hourly update: internships CSV"
            
            # Pull any remote changes first to avoid conflicts
            git pull --rebase origin main || echo "No remote changes to pull"
            
            # Push changes
            git push origin main
          else
            echo "No changes to commit"
          fi
